// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/redis/go-redis/v9"
	"github.com/senran-N/sub2api/ent"
	"github.com/senran-N/sub2api/internal/config"
	"github.com/senran-N/sub2api/internal/handler"
	"github.com/senran-N/sub2api/internal/handler/admin"
	"github.com/senran-N/sub2api/internal/repository"
	"github.com/senran-N/sub2api/internal/server"
	"github.com/senran-N/sub2api/internal/server/middleware"
	"github.com/senran-N/sub2api/internal/service"
	"net/http"
)

import (
	_ "embed"
	_ "github.com/senran-N/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	v := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, configConfig)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := repository.NewBillingCache(redisClient)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	billingCacheService := service.NewBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, configConfig)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	v2 := repository.NewAPIKeyCache(redisClient)
	apiKeyService := service.NewAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, v2, configConfig)
	lifecycleRegistry := service.ProvideLifecycleRegistry()
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService, lifecycleRegistry)
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	authService := service.NewAuthService(client, userRepository, redeemCodeRepository, v, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, subscriptionService)
	userService := service.NewUserService(userRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService)
	userHandler := handler.NewUserHandler(userService)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	usageService := service.NewUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.NewAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	timingWheelService, err := service.ProvideTimingWheelService(lifecycleRegistry)
	if err != nil {
		return nil, err
	}
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, configConfig, lifecycleRegistry)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	proxyRepository := repository.NewProxyRepository(client, db)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	privacyClientFactory := providePrivacyClientFactory()
	ipRiskService := service.NewIPRiskService(configConfig)
	adminService := service.NewAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, subscriptionService, userSubscriptionRepository, privacyClientFactory, ipRiskService)
	v3 := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(v3, accountRepository, configConfig, lifecycleRegistry)
	adminUserHandler := admin.ProvideUserHandler(adminService, concurrencyService)
	v4 := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, v4, rpmCache)
	groupHandler := admin.ProvideGroupHandler(adminService, dashboardService, groupCapacityService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.NewOpenAIOAuthService(proxyRepository, openAIOAuthClient)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	v5 := repository.NewTLSFingerprintProfileRepository(client)
	v6 := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(v5, v6)
	compatibleUpstreamModelsService := service.NewCompatibleUpstreamModelsService(accountRepository, httpUpstream, configConfig, tlsFingerprintProfileService)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	v7 := repository.NewTempUnschedCache(redisClient)
	v8 := repository.NewTimeoutCounterCache(redisClient)
	v9 := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(v9)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, v7, v8, settingService, compositeTokenCacheInvalidator)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository)
	usageCache := service.NewUsageCache()
	v10 := repository.NewIdentityCache(redisClient)
	accountUsageService := service.NewAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, usageCache, v10, tlsFingerprintProfileService)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, v9)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, v9, geminiOAuthService, oAuthRefreshAPI, v7)
	v11 := repository.NewGatewayCache(redisClient)
	v12 := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, v12, accountRepository, groupRepository, configConfig, lifecycleRegistry)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, v9, antigravityOAuthService, oAuthRefreshAPI, v7)
	v13 := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, v11, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, v13)
	accountTestService := service.NewAccountTestService(accountRepository, geminiTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, oAuthService, openAIOAuthService, geminiOAuthService, configConfig)
	accountHandler := admin.ProvideAccountHandler(adminService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, compatibleUpstreamModelsService, rateLimitService, accountUsageService, accountTestService, concurrencyService, crsSyncService, v4, rpmCache, compositeTokenCacheInvalidator)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper, lifecycleRegistry)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	openAIOAuthHandler := admin.ProvideOpenAIOAuthHandler(openAIOAuthService, adminService)
	geminiOAuthHandler := admin.NewGeminiOAuthHandler(geminiOAuthService)
	antigravityOAuthHandler := admin.NewAntigravityOAuthHandler(antigravityOAuthService)
	proxyHandler := admin.ProvideProxyHandler(adminService)
	adminRedeemHandler := admin.ProvideRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	opsRepository := repository.NewOpsRepository(db)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient, lifecycleRegistry)
	if err != nil {
		return nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	identityService := service.NewIdentityService(v10)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService, lifecycleRegistry)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, v9, oAuthService, oAuthRefreshAPI)
	digestSessionStore := service.NewDigestSessionStore()
	channelRepository := repository.NewChannelRepository(db)
	channelService := service.NewChannelService(channelRepository, apiKeyAuthCacheInvalidator)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService)
	gatewayService := service.NewGatewayService(accountRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, v11, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, v4, rpmCache, digestSessionStore, settingService, tlsFingerprintProfileService, channelService, modelPricingResolver)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, v9, openAIOAuthService, oAuthRefreshAPI)
	openAIGatewayService := service.NewOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, v11, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, modelPricingResolver, channelService)
	geminiMessagesCompatService := service.NewGeminiMessagesCompatService(accountRepository, groupRepository, v11, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository, configConfig, lifecycleRegistry)
	opsService := service.NewOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, opsSystemLogSink)
	settingHandler := admin.NewSettingHandler(settingService, emailService, turnstileService, opsService)
	opsHandler := admin.NewOpsHandler(opsService)
	v14 := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(v14, gitHubReleaseClient, serviceBuildInfo)
	v15 := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(v15, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, configConfig, lifecycleRegistry)
	adminUsageHandler := admin.ProvideUsageHandler(usageService, apiKeyService, adminService, usageCleanupService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	v16 := repository.NewErrorPassthroughRepository(client)
	v17 := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(v16, v17)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	adminAPIKeyHandler := admin.ProvideAdminAPIKeyHandler(adminService)
	v18 := repository.NewScheduledTestPlanRepository(db)
	v19 := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(v18, v19)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	channelHandler := admin.NewChannelHandler(channelService, billingService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, groupHandler, accountHandler, adminAnnouncementHandler, dataManagementHandler, backupHandler, oAuthHandler, openAIOAuthHandler, geminiOAuthHandler, antigravityOAuthHandler, proxyHandler, adminRedeemHandler, promoHandler, settingHandler, opsHandler, systemHandler, adminSubscriptionHandler, adminUsageHandler, userAttributeHandler, errorPassthroughHandler, tlsFingerprintProfileHandler, adminAPIKeyHandler, scheduledTestHandler, channelHandler)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig, lifecycleRegistry)
	gatewayHandler := handler.NewGatewayHandler(gatewayService, geminiMessagesCompatService, antigravityGatewayService, compatibleUpstreamModelsService, userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, userMessageQueueService, configConfig, settingService)
	compatibleGatewayTextHandler := handler.NewCompatibleGatewayTextHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, configConfig)
	openAIGatewayHandler := handler.NewOpenAIGatewayHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, configConfig)
	compatibleGatewayPassthroughRuntime := handler.ProvideCompatibleGatewayPassthroughRuntime(openAIGatewayHandler)
	compatibleGatewayRuntimeHandler := handler.NewCompatibleGatewayRuntimeHandler(compatibleGatewayTextHandler, compatibleGatewayPassthroughRuntime)
	compatibleGatewayTextRuntime := service.ProvideCompatibleGatewayTextRuntime(openAIGatewayService)
	grokCompatibleRuntime := service.ProvideGrokCompatibleRuntime(compatibleGatewayTextRuntime)
	grokSessionRuntime := service.NewGrokSessionRuntime(gatewayService)
	grokTextRuntime := service.NewGrokTextRuntime(gatewayService, grokCompatibleRuntime, grokSessionRuntime)
	grokVideoJobRepository := repository.NewGrokVideoJobRepository(db)
	grokMediaAssetRepository := repository.NewGrokMediaAssetRepository(db)
	grokGatewayService := service.ProvideGrokGatewayService(grokTextRuntime, gatewayService, grokVideoJobRepository, grokMediaAssetRepository)
	grokGatewayHandler := handler.NewGrokGatewayHandler(compatibleGatewayRuntimeHandler, gatewayService, grokGatewayService, compatibleUpstreamModelsService)
	compatibleGatewayHandler := handler.NewCompatibleGatewayHandler(compatibleGatewayRuntimeHandler, grokGatewayHandler, gatewayService, compatibleUpstreamModelsService)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo)
	totpHandler := handler.NewTotpHandler(totpService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(v15, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(v15, configConfig, lifecycleRegistry)
	handlers := handler.ProvideHandlers(authHandler, userHandler, apiKeyHandler, usageHandler, redeemHandler, subscriptionHandler, announcementHandler, adminHandlers, gatewayHandler, compatibleGatewayHandler, grokGatewayHandler, handlerSettingHandler, totpHandler, idempotencyCoordinator, idempotencyCleanupService)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	gatewayRouteDependencies := server.ProvideGatewayRouteDependencies(apiKeyAuthMiddleware, apiKeyService, subscriptionService, opsService, settingService, configConfig)
	routeDependencies := server.ProvideRouteDependencies(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, redisClient, gatewayRouteDependencies)
	engine := server.ProvideRouter(configConfig, routeDependencies)
	httpServer := server.ProvideHTTPServer(configConfig, engine)
	claudeCodeProfileSyncService := service.ProvideClaudeCodeProfileSyncStarter(configConfig)
	v20 := provideCleanup(configConfig, client, redisClient, lifecycleRegistry, claudeCodeProfileSyncService, emailQueueService, billingCacheService, usageRecordWorkerPool, subscriptionService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, openAIGatewayService)
	application := &Application{
		Server:  httpServer,
		Cleanup: v20,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server  *http.Server
	Cleanup func()
}

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(
	cfg *config.Config,
	entClient *ent.Client,
	rdb *redis.Client,
	lifecycleRegistry *service.LifecycleRegistry,
	claudeProfileSync *service.ClaudeCodeProfileSyncService,
	emailQueue *service.EmailQueueService,
	billingCache *service.BillingCacheService,
	usageRecordWorkerPool *service.UsageRecordWorkerPool,
	subscriptionService *service.SubscriptionService,
	oauth *service.OAuthService,
	openaiOAuth *service.OpenAIOAuthService,
	geminiOAuth *service.GeminiOAuthService,
	antigravityOAuth *service.AntigravityOAuthService,
	openAIGateway *service.OpenAIGatewayService,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), resolveShutdownTimeout(cfg))
		defer cancel()

		parallelSteps := lifecycleRegistrySteps(lifecycleRegistry)
		parallelSteps = append(parallelSteps, []cleanupStep{
			stopStep("ClaudeCodeProfileSyncService", claudeProfileSync),
			stopStep("SubscriptionService", subscriptionService),
			stopStep("EmailQueueService", emailQueue),
			stopStep("BillingCacheService", billingCache),
			stopStep("UsageRecordWorkerPool", usageRecordWorkerPool),
			stopStep("OAuthService", oauth),
			stopStep("OpenAIOAuthService", openaiOAuth),
			stopStep("GeminiOAuthService", geminiOAuth),
			stopStep("AntigravityOAuthService", antigravityOAuth),
			callbackStep("OpenAIWSPool", func() {
				if openAIGateway != nil {
					openAIGateway.CloseOpenAIWSPool()
				}
			}),
		}...)

		infraSteps := []cleanupStep{
			closeStep("Redis", rdb),
			closeStep("Ent", entClient),
		}

		runCleanup(ctx, parallelSteps, infraSteps)
	}
}

func lifecycleRegistrySteps(registry *service.LifecycleRegistry) []cleanupStep {
	entries := registry.Entries()
	steps := make([]cleanupStep, 0, len(entries))
	for _, entry := range entries {
		entry := entry
		steps = append(steps, callbackStep(entry.Name, entry.Stop))
	}
	return steps
}
