DROP TABLE IF EXISTS usage_logs;
DROP TABLE IF EXISTS redeem_codes;
DROP TABLE IF EXISTS account_groups;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS proxies;
